In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier

In [2]:
data_accidents = pd.read_csv('data/AccidentsBig.csv')

/tmp/ipykernel_12223/2632685192.py:1: DtypeWarning: Columns (0: Time, 1: Local_Authority_(Highway), 2: LSOA_of_Accident_Location, 3: Date) have mixed types. Specify dtype option on import or set low_memory=False.
  data_accidents = pd.read_csv('data/AccidentsBig.csv')

In [3]:
data_accidents

,Accident_Index,longitude,latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Day_of_Week,Time,Local_Authority_(District),...,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Date
0,1.0,78.610393,14.724026,1.0,2.0,1.0,1.0,3.0,17:42,12.0,...,1.0,1.0,2.0,2.0,0.0,0.0,1.0,1.0,E01002849,04-01-2018
1,2.0,78.534042,14.762353,1.0,3.0,1.0,1.0,4.0,17:36,12.0,...,5.0,4.0,1.0,1.0,0.0,0.0,1.0,1.0,E01002909,05-01-2018
2,3.0,78.470877,14.745606,1.0,3.0,2.0,1.0,5.0,00:15,12.0,...,0.0,4.0,1.0,1.0,0.0,0.0,1.0,1.0,E01002857,06-01-2018
3,4.0,78.557994,14.667128,1.0,3.0,1.0,1.0,6.0,10:35,12.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,E01002840,07-01-2018
4,5.0,78.576431,14.703443,1.0,3.0,1.0,1.0,2.0,21:13,12.0,...,0.0,7.0,1.0,2.0,0.0,0.0,1.0,1.0,E01002863,10-01-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data_casualities = pd.read_csv('data/CasualtiesBig.csv')

In [6]:
data_casualities

,Accident_Index,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,Casualty_Type,Casualty_Home_Area_Type
0,1,1,1,3,1,37,7,2,1,1,0,0,-1,0,1
1,2,1,1,2,1,37,7,3,0,0,0,4,-1,11,1
2,3,2,1,1,1,62,9,3,0,0,0,0,-1,9,1
3,4,1,1,3,1,30,6,3,5,2,0,0,-1,0,1
4,5,1,1,1,1,49,8,3,0,0,0,0,-1,3,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59993,59994,1,2,2,2,11,3,3,0,0,1,0,-1,9,1
59994,59995,1,3,2,1,10,2,3,0,0,2,0,-1,9,1
59995,59996,2,1,1,1,45,7,3,0,0,0,0,-1,1,1
59996,59997,2,1,2,1,39,7,3,0,0,1,0,-1,9,1
59997,59998,2,1,1,1,66,10,3,0,0,0,0,-1,9,3

In [9]:
data_vehicle = pd.read_csv('data/VehiclesBig.csv')

In [10]:
data_vehicle

,Accident_Index,Vehicle_Reference,Vehicle_Type,Towing_and_Articulation,Vehicle_Manoeuvre,Vehicle_Location-Restricted_Lane,Junction_Location,Skidding_and_Overturning,Hit_Object_in_Carriageway,Vehicle_Leaving_Carriageway,...,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type
0,1.000000e+00,1.0,9.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,15.0,2.0,74.0,10.0,-1.0,-1.0,-1.0,7.0,1.0
1,2.000000e+00,1.0,11.0,0.0,4.0,0.0,3.0,0.0,0.0,0.0,...,1.0,1.0,1.0,42.0,7.0,8268.0,2.0,3.0,-1.0,-1.0
2,3.000000e+00,1.0,11.0,0.0,17.0,0.0,0.0,0.0,4.0,0.0,...,1.0,1.0,1.0,35.0,6.0,8300.0,2.0,5.0,2.0,1.0
3,4.000000e+00,2.0,9.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,1.0,15.0,1.0,62.0,9.0,1762.0,1.0,6.0,1.0,1.0
4,5.000000e+00,1.0,9.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,15.0,2.0,49.0,8.0,1769.0,1.0,4.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,2.010000e+12,1.0,9.0,0.0,5.0,9.0,6.0,0.0,0.0,0.0,...,1.0,1.0,1.0,58.0,9.0,998.0,1.0,3.0,-1.0,3.0

In [15]:
#Here we can observe that Accident_index can be used to merge.
#Lot of feature engineering is required. Let's seeeee
df = pd.merge(data_casualities, data_accidents, how='inner', on='Accident_Index')
data = pd.merge(df, data_vehicle, on='Accident_Index', how='inner')

In [17]:
data

,Accident_Index,Vehicle_Reference_x,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,...,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type
0,1,1,1,3,1,37,7,2,1,1,...,1.0,15.0,2.0,74.0,10.0,-1.0,-1.0,-1.0,7.0,1.0
1,2,1,1,2,1,37,7,3,0,0,...,1.0,1.0,1.0,42.0,7.0,8268.0,2.0,3.0,-1.0,-1.0
2,3,2,1,1,1,62,9,3,0,0,...,1.0,1.0,1.0,35.0,6.0,8300.0,2.0,5.0,2.0,1.0
3,4,1,1,3,1,30,6,3,5,2,...,1.0,15.0,1.0,62.0,9.0,1762.0,1.0,6.0,1.0,1.0
4,5,1,1,1,1,49,8,3,0,0,...,1.0,15.0,2.0,49.0,8.0,1769.0,1.0,4.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59993,59994,1,2,2,2,11,3,3,0,0,...,-1.0,-1.0,2.0,67.0,10.0,-1.0,-1.0,-1.0,10.0,1.0
59994,59995,1,3,2,1,10,2,3,0,0,...,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
59995,59996,2,1,1,1,45,7,3,0,0,...,-1.0,-1.0,1.0,37.0,7.0,1799.0,1.0,7.0,7.0,1.0
59996,59997,2,1,2,1,39,7,3,0,0,...,-1.0,-1.0,1.0,36.0,7.0,1998.0,2.0,2.0,-1.0,-1.0
59997,59998,2,1,1,1,66,10,3,0,0,...,-1.0,-1.0,2.0,40.0,7.0,1124.0,1.0,3.0,8.0,1.0

In [18]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 59998 entries, 0 to 59997
Data columns (total 65 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Accident_Index                               59998 non-null  int64
 1   Vehicle_Reference_x                          59998 non-null  int64
 2   Casualty_Reference                           59998 non-null  int64
 3   Casualty_Class                               59998 non-null  int64
 4   Sex_of_Casualty                              59998 non-null  int64
 5   Age_of_Casualty                              59998 non-null  int64
 6   Age_Band_of_Casualty                         59998 non-null  int64
 7   Casualty_Severity                            59998 non-null  int64
 8   Pedestrian_Location                          59998 non-null  int64
 9   Pedestrian_Movement                          59998 non-null  int64
 10  Car_Passenger                                59998 non-null  int64
 11  Bus_or_Coach_Passenger                       59998 non-null  int64
 12  Pedestrian_Road_Maintenance_Worker           59998 non-null  int64
 13  Casualty_Type                                59998 non-null  int64
 14  Casualty_Home_Area_Type                      59998 non-null  int64
 15  longitude                                    59998 non-null  float64
 16  latitude                                     59998 non-null  float64
 17  Police_Force                                 59998 non-null  float64
 18  Accident_Severity                            59998 non-null  float64
 19  Number_of_Vehicles                           59998 non-null  float64
 20  Number_of_Casualties                         59998 non-null  float64
 21  Day_of_Week                                  59998 non-null  float64
 22  Time                                         59997 non-null  str
 23  Local_Authority_(District)                   59998 non-null  float64
 24  Local_Authority_(Highway)                    59998 non-null  str
 25  1st_Road_Class                               59998 non-null  float64
 26  1st_Road_Number                              59998 non-null  float64
 27  Road_Type                                    59998 non-null  float64
 28  Speed_limit                                  59998 non-null  float64
 29  Junction_Detail                              59998 non-null  float64
 30  Junction_Control                             59998 non-null  float64
 31  2nd_Road_Class                               59998 non-null  float64
 32  2nd_Road_Number                              59998 non-null  float64
 33  Pedestrian_Crossing-Human_Control            59998 non-null  float64
 34  Pedestrian_Crossing-Physical_Facilities      59998 non-null  float64
 35  Light_Conditions                             59998 non-null  float64
 36  Weather_Conditions                           59998 non-null  float64
 37  Road_Surface_Conditions                      59998 non-null  float64
 38  Special_Conditions_at_Site                   59998 non-null  float64
 39  Carriageway_Hazards                          59998 non-null  float64
 40  Urban_or_Rural_Area                          59998 non-null  float64
 41  Did_Police_Officer_Attend_Scene_of_Accident  59998 non-null  float64
 42  LSOA_of_Accident_Location                    59901 non-null  str
 43  Date                                         59998 non-null  str
 44  Vehicle_Reference_y                          59998 non-null  float64
 45  Vehicle_Type                                 59998 non-null  float64
 46  Towing_and_Articulation                      59998 non-null  float64
 47  Vehicle_Manoeuvre                            59998 non-null  float64
 48  Vehicle_Location-Restricted_Lane             59998 non-null  float64
 49  Junction_Location                            59998 non-null  float64
 50  Skidding_and_Overturning                     59998 non-null  float64
 51  Hit_Object_in_Carriageway                    59998 non-null  float64
 52  Vehicle_Leaving_Carriageway                  59998 non-null  float64
 53  Hit_Object_off_Carriageway                   59998 non-null  float64
 54  1st_Point_of_Impact                          59998 non-null  float64
 55  Was_Vehicle_Left_Hand_Drive?                 59998 non-null  float64
 56  Journey_Purpose_of_Driver                    59998 non-null  float64
 57  Sex_of_Driver                                59998 non-null  float64
 58  Age_of_Driver                                59998 non-null  float64
 59  Age_Band_of_Driver                           59998 non-null  float64
 60  Engine_Capacity_(CC)                         59998 non-null  float64
 61  Propulsion_Code                              59998 non-null  float64
 62  Age_of_Vehicle                               59998 non-null  float64
 63  Driver_IMD_Decile                            59998 non-null  float64
 64  Driver_Home_Area_Type                        59998 non-null  float64
dtypes: float64(46), int64(15), str(4)
memory usage: 29.8 MB

In [20]:
#Thank God. We have only few Null values. Still I'll confirm
print(data.isnull().sum())

Accident_Index           0
Vehicle_Reference_x      0
Casualty_Reference       0
Casualty_Class           0
Sex_of_Casualty          0
                        ..
Engine_Capacity_(CC)     0
Propulsion_Code          0
Age_of_Vehicle           0
Driver_IMD_Decile        0
Driver_Home_Area_Type    0
Length: 65, dtype: int64

In [21]:
data.dropna(subset=['LSOA_of_Accident_Location', 'Time'], inplace=True)

In [22]:
data.info()

<class 'pandas.DataFrame'>
Index: 59900 entries, 0 to 59997
Data columns (total 65 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Accident_Index                               59900 non-null  int64
 1   Vehicle_Reference_x                          59900 non-null  int64
 2   Casualty_Reference                           59900 non-null  int64
 3   Casualty_Class                               59900 non-null  int64
 4   Sex_of_Casualty                              59900 non-null  int64
 5   Age_of_Casualty                              59900 non-null  int64
 6   Age_Band_of_Casualty                         59900 non-null  int64
 7   Casualty_Severity                            59900 non-null  int64
 8   Pedestrian_Location                          59900 non-null  int64
 9   Pedestrian_Movement                          59900 non-null  int64
 10  Car_Passenger                                59900 non-null  int64
 11  Bus_or_Coach_Passenger                       59900 non-null  int64
 12  Pedestrian_Road_Maintenance_Worker           59900 non-null  int64
 13  Casualty_Type                                59900 non-null  int64
 14  Casualty_Home_Area_Type                      59900 non-null  int64
 15  longitude                                    59900 non-null  float64
 16  latitude                                     59900 non-null  float64
 17  Police_Force                                 59900 non-null  float64
 18  Accident_Severity                            59900 non-null  float64
 19  Number_of_Vehicles                           59900 non-null  float64
 20  Number_of_Casualties                         59900 non-null  float64
 21  Day_of_Week                                  59900 non-null  float64
 22  Time                                         59900 non-null  str
 23  Local_Authority_(District)                   59900 non-null  float64
 24  Local_Authority_(Highway)                    59900 non-null  str
 25  1st_Road_Class                               59900 non-null  float64
 26  1st_Road_Number                              59900 non-null  float64
 27  Road_Type                                    59900 non-null  float64
 28  Speed_limit                                  59900 non-null  float64
 29  Junction_Detail                              59900 non-null  float64
 30  Junction_Control                             59900 non-null  float64
 31  2nd_Road_Class                               59900 non-null  float64
 32  2nd_Road_Number                              59900 non-null  float64
 33  Pedestrian_Crossing-Human_Control            59900 non-null  float64
 34  Pedestrian_Crossing-Physical_Facilities      59900 non-null  float64
 35  Light_Conditions                             59900 non-null  float64
 36  Weather_Conditions                           59900 non-null  float64
 37  Road_Surface_Conditions                      59900 non-null  float64
 38  Special_Conditions_at_Site                   59900 non-null  float64
 39  Carriageway_Hazards                          59900 non-null  float64
 40  Urban_or_Rural_Area                          59900 non-null  float64
 41  Did_Police_Officer_Attend_Scene_of_Accident  59900 non-null  float64
 42  LSOA_of_Accident_Location                    59900 non-null  str
 43  Date                                         59900 non-null  str
 44  Vehicle_Reference_y                          59900 non-null  float64
 45  Vehicle_Type                                 59900 non-null  float64
 46  Towing_and_Articulation                      59900 non-null  float64
 47  Vehicle_Manoeuvre                            59900 non-null  float64
 48  Vehicle_Location-Restricted_Lane             59900 non-null  float64
 49  Junction_Location                            59900 non-null  float64
 50  Skidding_and_Overturning                     59900 non-null  float64
 51  Hit_Object_in_Carriageway                    59900 non-null  float64
 52  Vehicle_Leaving_Carriageway                  59900 non-null  float64
 53  Hit_Object_off_Carriageway                   59900 non-null  float64
 54  1st_Point_of_Impact                          59900 non-null  float64
 55  Was_Vehicle_Left_Hand_Drive?                 59900 non-null  float64
 56  Journey_Purpose_of_Driver                    59900 non-null  float64
 57  Sex_of_Driver                                59900 non-null  float64
 58  Age_of_Driver                                59900 non-null  float64
 59  Age_Band_of_Driver                           59900 non-null  float64
 60  Engine_Capacity_(CC)                         59900 non-null  float64
 61  Propulsion_Code                              59900 non-null  float64
 62  Age_of_Vehicle                               59900 non-null  float64
 63  Driver_IMD_Decile                            59900 non-null  float64
 64  Driver_Home_Area_Type                        59900 non-null  float64
dtypes: float64(46), int64(15), str(4)
memory usage: 30.2 MB

In [23]:
data.isnull().sum()

Accident_Index           0
Vehicle_Reference_x      0
Casualty_Reference       0
Casualty_Class           0
Sex_of_Casualty          0
                        ..
Engine_Capacity_(CC)     0
Propulsion_Code          0
Age_of_Vehicle           0
Driver_IMD_Decile        0
Driver_Home_Area_Type    0
Length: 65, dtype: int64

In [24]:
#Thank god. No more Null values
data.columns

Index(['Accident_Index', 'Vehicle_Reference_x', 'Casualty_Reference',
       'Casualty_Class', 'Sex_of_Casualty', 'Age_of_Casualty',
       'Age_Band_of_Casualty', 'Casualty_Severity', 'Pedestrian_Location',
       'Pedestrian_Movement', 'Car_Passenger', 'Bus_or_Coach_Passenger',
       'Pedestrian_Road_Maintenance_Worker', 'Casualty_Type',
       'Casualty_Home_Area_Type', 'longitude', 'latitude', 'Police_Force',
       'Accident_Severity', 'Number_of_Vehicles', 'Number_of_Casualties',
       'Day_of_Week', 'Time', 'Local_Authority_(District)',
       'Local_Authority_(Highway)', '1st_Road_Class', '1st_Road_Number',
       'Road_Type', 'Speed_limit', 'Junction_Detail', 'Junction_Control',
       '2nd_Road_Class', '2nd_Road_Number',
       'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions',
       'Special_Conditions_at_Site', 'Carriageway_Hazards',
       'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident',
       'LSOA_of_Accident_Location', 'Date', 'Vehicle_Reference_y',
       'Vehicle_Type', 'Towing_and_Articulation', 'Vehicle_Manoeuvre',
       'Vehicle_Location-Restricted_Lane', 'Junction_Location',
       'Skidding_and_Overturning', 'Hit_Object_in_Carriageway',
       'Vehicle_Leaving_Carriageway', 'Hit_Object_off_Carriageway',
       '1st_Point_of_Impact', 'Was_Vehicle_Left_Hand_Drive?',
       'Journey_Purpose_of_Driver', 'Sex_of_Driver', 'Age_of_Driver',
       'Age_Band_of_Driver', 'Engine_Capacity_(CC)', 'Propulsion_Code',
       'Age_of_Vehicle', 'Driver_IMD_Decile', 'Driver_Home_Area_Type'],
      dtype='str')

In [26]:
#We can see that the featurs in the merged df are not important. So I'll remove them
cols_to_drop = [
    'Accident_Index',
    'LSOA_of_Accident_Location',
    'Time',
    'Date',
    'longitude',
    'latitude',
    'Vehicle_Reference_y',
    'Vehicle_Reference_x',
    'Casualty_Reference'
]
data.drop(columns=cols_to_drop, inplace=True)

In [27]:
data

,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,...,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type
0,3,1,37,7,2,1,1,0,0,-1,...,1.0,15.0,2.0,74.0,10.0,-1.0,-1.0,-1.0,7.0,1.0
1,2,1,37,7,3,0,0,0,4,-1,...,1.0,1.0,1.0,42.0,7.0,8268.0,2.0,3.0,-1.0,-1.0
2,1,1,62,9,3,0,0,0,0,-1,...,1.0,1.0,1.0,35.0,6.0,8300.0,2.0,5.0,2.0,1.0
3,3,1,30,6,3,5,2,0,0,-1,...,1.0,15.0,1.0,62.0,9.0,1762.0,1.0,6.0,1.0,1.0
4,1,1,49,8,3,0,0,0,0,-1,...,1.0,15.0,2.0,49.0,8.0,1769.0,1.0,4.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59993,2,2,11,3,3,0,0,1,0,-1,...,-1.0,-1.0,2.0,67.0,10.0,-1.0,-1.0,-1.0,10.0,1.0
59994,2,1,10,2,3,0,0,2,0,-1,...,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
59995,1,1,45,7,3,0,0,0,0,-1,...,-1.0,-1.0,1.0,37.0,7.0,1799.0,1.0,7.0,7.0,1.0
59996,2,1,39,7,3,0,0,1,0,-1,...,-1.0,-1.0,1.0,36.0,7.0,1998.0,2.0,2.0,-1.0,-1.0
59997,1,1,66,10,3,0,0,0,0,-1,...,-1.0,-1.0,2.0,40.0,7.0,1124.0,1.0,3.0,8.0,1.0

In [28]:
data.drop(columns='Local_Authority_(Highway)', inplace=True)

In [29]:
data

,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,...,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type
0,3,1,37,7,2,1,1,0,0,-1,...,1.0,15.0,2.0,74.0,10.0,-1.0,-1.0,-1.0,7.0,1.0
1,2,1,37,7,3,0,0,0,4,-1,...,1.0,1.0,1.0,42.0,7.0,8268.0,2.0,3.0,-1.0,-1.0
2,1,1,62,9,3,0,0,0,0,-1,...,1.0,1.0,1.0,35.0,6.0,8300.0,2.0,5.0,2.0,1.0
3,3,1,30,6,3,5,2,0,0,-1,...,1.0,15.0,1.0,62.0,9.0,1762.0,1.0,6.0,1.0,1.0
4,1,1,49,8,3,0,0,0,0,-1,...,1.0,15.0,2.0,49.0,8.0,1769.0,1.0,4.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59993,2,2,11,3,3,0,0,1,0,-1,...,-1.0,-1.0,2.0,67.0,10.0,-1.0,-1.0,-1.0,10.0,1.0
59994,2,1,10,2,3,0,0,2,0,-1,...,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
59995,1,1,45,7,3,0,0,0,0,-1,...,-1.0,-1.0,1.0,37.0,7.0,1799.0,1.0,7.0,7.0,1.0
59996,2,1,39,7,3,0,0,1,0,-1,...,-1.0,-1.0,1.0,36.0,7.0,1998.0,2.0,2.0,-1.0,-1.0
59997,1,1,66,10,3,0,0,0,0,-1,...,-1.0,-1.0,2.0,40.0,7.0,1124.0,1.0,3.0,8.0,1.0

In [59]:
x = data.drop('Accident_Severity', axis = 1)
y = data['Accident_Severity']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42, stratify=y)

In [60]:
y_test

42781    3.0
38820    2.0
15044    3.0
58954    2.0
2909     3.0
        ...
25836    3.0
44073    3.0
5428     3.0
59108    3.0
9731     3.0
Name: Accident_Severity, Length: 11980, dtype: float64

In [61]:
y_train

16225    3.0
24818    2.0
54326    3.0
25127    3.0
29425    3.0
        ...
18933    3.0
50575    3.0
47734    3.0
58470    3.0
44491    2.0
Name: Accident_Severity, Length: 47920, dtype: float64

In [62]:
data.info()

<class 'pandas.DataFrame'>
Index: 59900 entries, 0 to 59997
Data columns (total 55 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Casualty_Class                               59900 non-null  int64
 1   Sex_of_Casualty                              59900 non-null  int64
 2   Age_of_Casualty                              59900 non-null  int64
 3   Age_Band_of_Casualty                         59900 non-null  int64
 4   Casualty_Severity                            59900 non-null  int64
 5   Pedestrian_Location                          59900 non-null  int64
 6   Pedestrian_Movement                          59900 non-null  int64
 7   Car_Passenger                                59900 non-null  int64
 8   Bus_or_Coach_Passenger                       59900 non-null  int64
 9   Pedestrian_Road_Maintenance_Worker           59900 non-null  int64
 10  Casualty_Type                                59900 non-null  int64
 11  Casualty_Home_Area_Type                      59900 non-null  int64
 12  Police_Force                                 59900 non-null  float64
 13  Accident_Severity                            59900 non-null  float64
 14  Number_of_Vehicles                           59900 non-null  float64
 15  Number_of_Casualties                         59900 non-null  float64
 16  Day_of_Week                                  59900 non-null  float64
 17  Local_Authority_(District)                   59900 non-null  float64
 18  1st_Road_Class                               59900 non-null  float64
 19  1st_Road_Number                              59900 non-null  float64
 20  Road_Type                                    59900 non-null  float64
 21  Speed_limit                                  59900 non-null  float64
 22  Junction_Detail                              59900 non-null  float64
 23  Junction_Control                             59900 non-null  float64
 24  2nd_Road_Class                               59900 non-null  float64
 25  2nd_Road_Number                              59900 non-null  float64
 26  Pedestrian_Crossing-Human_Control            59900 non-null  float64
 27  Pedestrian_Crossing-Physical_Facilities      59900 non-null  float64
 28  Light_Conditions                             59900 non-null  float64
 29  Weather_Conditions                           59900 non-null  float64
 30  Road_Surface_Conditions                      59900 non-null  float64
 31  Special_Conditions_at_Site                   59900 non-null  float64
 32  Carriageway_Hazards                          59900 non-null  float64
 33  Urban_or_Rural_Area                          59900 non-null  float64
 34  Did_Police_Officer_Attend_Scene_of_Accident  59900 non-null  float64
 35  Vehicle_Type                                 59900 non-null  float64
 36  Towing_and_Articulation                      59900 non-null  float64
 37  Vehicle_Manoeuvre                            59900 non-null  float64
 38  Vehicle_Location-Restricted_Lane             59900 non-null  float64
 39  Junction_Location                            59900 non-null  float64
 40  Skidding_and_Overturning                     59900 non-null  float64
 41  Hit_Object_in_Carriageway                    59900 non-null  float64
 42  Vehicle_Leaving_Carriageway                  59900 non-null  float64
 43  Hit_Object_off_Carriageway                   59900 non-null  float64
 44  1st_Point_of_Impact                          59900 non-null  float64
 45  Was_Vehicle_Left_Hand_Drive?                 59900 non-null  float64
 46  Journey_Purpose_of_Driver                    59900 non-null  float64
 47  Sex_of_Driver                                59900 non-null  float64
 48  Age_of_Driver                                59900 non-null  float64
 49  Age_Band_of_Driver                           59900 non-null  float64
 50  Engine_Capacity_(CC)                         59900 non-null  float64
 51  Propulsion_Code                              59900 non-null  float64
 52  Age_of_Vehicle                               59900 non-null  float64
 53  Driver_IMD_Decile                            59900 non-null  float64
 54  Driver_Home_Area_Type                        59900 non-null  float64
dtypes: float64(43), int64(12)
memory usage: 25.6 MB

In [63]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
pipe = Pipeline(
    [
        ('scaler', StandardScaler()),
        ('classifier', LogisticRegression(
            max_iter=1000,
            class_weight='balanced',
        ))
    ]
)
pipe.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [64]:
random_forest = RandomForestClassifier(
    n_estimators=200,
    max_depth=20,
    class_weight='balanced',
    random_state=42
)
gradient = GradientBoostingClassifier(
    n_estimators=50,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)
ada = AdaBoostClassifier(
    n_estimators=200,
    learning_rate=0.1,
    random_state=42
)
xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=10,
    random_state=42
)

In [65]:
random_forest.fit(x_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=20, n_estimators=200,
                       random_state=42)

In [66]:
gradient.fit(x_train, y_train)

GradientBoostingClassifier(max_depth=6, n_estimators=50, random_state=42)

In [67]:
ada.fit(x_train, y_train)

AdaBoostClassifier(learning_rate=0.1, n_estimators=200, random_state=42)

In [68]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
y_train_conv = label.fit_transform(y_train)
y_test_conv = label.transform(y_test)
xgb.fit(x_train, y_train_conv)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [69]:
from sklearn.metrics import classification_report
models = {
    "logistic regression": pipe,
    "gradient boosting": gradient,
    "random forest": random_forest,
    "ada boosting": ada,
}
for name, model in models.items():
    y_pred = model.predict(x_test)
    print(name)
    print(classification_report(y_test, y_pred))
    print("============")

logistic regression
              precision    recall  f1-score   support

         1.0       0.03      0.53      0.06       129
         2.0       0.16      0.35      0.22      1473
         3.0       0.92      0.57      0.70     10378

    accuracy                           0.54     11980
   macro avg       0.37      0.49      0.33     11980
weighted avg       0.82      0.54      0.64     11980

============
gradient boosting
              precision    recall  f1-score   support

         1.0       0.09      0.02      0.03       129
         2.0       0.30      0.01      0.01      1473
         3.0       0.87      1.00      0.93     10378

    accuracy                           0.86     11980
   macro avg       0.42      0.34      0.32     11980
weighted avg       0.79      0.86      0.81     11980

============
random forest
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00       129
         2.0       0.28      0.00      0.01      1473
         3.0       0.87      1.00      0.93     10378

    accuracy                           0.87     11980
   macro avg       0.38      0.33      0.31     11980
weighted avg       0.78      0.87      0.80     11980

============
ada boosting
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00       129
         2.0       0.00      0.00      0.00      1473
         3.0       0.87      1.00      0.93     10378

    accuracy                           0.87     11980
   macro avg       0.29      0.33      0.31     11980
weighted avg       0.75      0.87      0.80     11980

============

/home/lenovo/PycharmProjects/Accident_Prediction/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/lenovo/PycharmProjects/Accident_Prediction/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/lenovo/PycharmProjects/Accident_Prediction/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [70]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)

x_train_res, y_train_res = smote.fit_resample(
    x_train, y_train
)

In [71]:
logistic_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('clf', LogisticRegression(
        max_iter=1000,
        class_weight='balanced'
    ))
])

logistic_pipe.fit(x_train_res, y_train_res)

Pipeline(steps=[('scaler', StandardScaler()),
                ('clf',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [72]:
random_forest = RandomForestClassifier(
    n_estimators=300,
    max_depth=20,
    class_weight='balanced',
    random_state=42
)

random_forest.fit(x_train_res, y_train_res)

RandomForestClassifier(class_weight='balanced', max_depth=20, n_estimators=300,
                       random_state=42)

In [73]:
from sklearn.ensemble import HistGradientBoostingClassifier
gradient = HistGradientBoostingClassifier(
    max_depth=6,
    learning_rate=0.1,
    class_weight='balanced',
    random_state=42
)

gradient.fit(x_train_res, y_train_res)

HistGradientBoostingClassifier(class_weight='balanced', max_depth=6,
                               random_state=42)

In [74]:
ada = AdaBoostClassifier(
    n_estimators=300,
    learning_rate=0.1,
    random_state=42
)

ada.fit(x_train_res, y_train_res)

AdaBoostClassifier(learning_rate=0.1, n_estimators=300, random_state=42)

In [75]:
from sklearn.utils.class_weight import compute_sample_weight
label_encoder = LabelEncoder()
y_train_enc = label_encoder.fit_transform(y_train)
y_test_enc = label_encoder.transform(y_test)

sample_weights = compute_sample_weight(
    class_weight='balanced',
    y=y_train_enc
)

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=8,
    objective='multi:softprob',
    num_class=3,
    eval_metric='mlogloss',
    random_state=42
)

xgb.fit(
    x_train,
    y_train_enc,
    sample_weight=sample_weights
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=8, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None, num_class=3, ...)

In [76]:
models = {
    "Logistic Regression": logistic_pipe,
    "Random Forest": random_forest,
    "Gradient Boosting": gradient,
    "AdaBoost": ada
}

for name, model in models.items():
    y_pred = model.predict(x_test)
    print(f"\n{name}")
    print(classification_report(y_test, y_pred))
    print("========")

y_pred_xgb_enc = xgb.predict(x_test)
y_pred_xgb = label_encoder.inverse_transform(y_pred_xgb_enc)

print("\nXGBOOST")
print(classification_report(y_test, y_pred_xgb))
print("=======")

Logistic Regression
              precision    recall  f1-score   support

         1.0       0.03      0.46      0.06       129
         2.0       0.14      0.26      0.18      1473
         3.0       0.90      0.65      0.75     10378

    accuracy                           0.60     11980
   macro avg       0.36      0.46      0.33     11980
weighted avg       0.79      0.60      0.68     11980

========

Random Forest
              precision    recall  f1-score   support

         1.0       0.20      0.02      0.04       129
         2.0       0.27      0.01      0.02      1473
         3.0       0.87      1.00      0.93     10378

    accuracy                           0.86     11980
   macro avg       0.45      0.34      0.33     11980
weighted avg       0.79      0.86      0.81     11980

========

Gradient Boosting
              precision    recall  f1-score   support

         1.0       0.60      0.02      0.04       129
         2.0       0.33      0.01      0.02      1473
         3.0       0.87      1.00      0.93     10378

    accuracy                           0.87     11980
   macro avg       0.60      0.34      0.33     11980
weighted avg       0.80      0.87      0.81     11980

========

AdaBoost
              precision    recall  f1-score   support

         1.0       0.04      0.29      0.08       129
         2.0       0.19      0.27      0.22      1473
         3.0       0.89      0.78      0.83     10378

    accuracy                           0.71     11980
   macro avg       0.38      0.44      0.38     11980
weighted avg       0.80      0.71      0.75     11980

========

XGBOOST
              precision    recall  f1-score   support

         1.0       0.05      0.12      0.08       129
         2.0       0.20      0.36      0.25      1473
         3.0       0.90      0.78      0.83     10378

    accuracy                           0.72     11980
   macro avg       0.38      0.42      0.39     11980
weighted avg       0.80      0.72      0.75     11980

=======